dubbo:
  application:
    #服务名称
    name: dubbo-springboot-demo-provider
    #应用协议
  protocol:
    name: dubbo
    #端口 -1 标识自动获取可用端口，默认8080
    port: -1
  registry:
    id: nacos-registry
    address: nacos://118.178.86.153:8848
  config-center:
    address: nacos://118.178.86.153:8848
  metadata-report:
    address: nacos://118.178.86.153:8848
nacos:
  discovery:
    server-addr: 118.178.86.153:8848

